modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]] #mandatory
modId="kimchi"
version="${file.jarVersion}"
displayName="Kimchi"
logoFile="examplemod.png"
credits="Kimchi by Thijs and Sohyung"
description='''
Maybe one time this mod will implement kimchi making for minecraft
'''

[[dependencies.kimchi]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.kimchi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
